management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
